Vagrant.configure("2") do |config|
  # Configuration commune à toutes les machines
  config.vm.box = "b2-tp2-centos"

  # Config une première VM "node1"
  config.vm.define "node1" do |node1|
  config.vm.hostname="node1.tp2.b2"
    # remarquez l'utilisation de 'node1.' défini sur la ligne au dessus
    node1.vm.network "private_network", ip: "192.168.2.21"
  end
  #config taille de la ram
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
  #config du nom de la machine 
  config.vm.provider :virtualbox do |vb|
    vb.name = "node1"
  end

  # Config une première VM "node2"
  config.vm.define "node2" do |node2|
  config.vm.hostname="node2.tp2.b2"
    # remarquez l'utilisation de 'node2.' défini sur la ligne au dessus
    node2.vm.network "private_network", ip: "192.168.2.22"
  end
  #config du nom de la machine 
  config.vm.provider :virtualbox do |vb|
    vb.name = "node2"
  end
  #config taille de la ram
  config.vm.provider "virtualbox" do |v|
    v.memory = 512
  end
end
